// src/app/page.tsx
import Link from "next/link";
import { auth } from "@/lib/auth";
import { redirect } from "next/navigation";

export default async function HomePage() {
  // If logged in, redirect to dashboard
  const session = await auth();
  if (session) redirect("/dashboard");

  return (
    <main className="min-h-screen bg-gradient-to-br from-gray-950 via-gray-900 to-indigo-950">
      {/* Hero Section */}
      <div className="relative isolate overflow-hidden">
        {/* Background decoration */}
        <div className="absolute inset-x-0 -top-40 -z-10 transform-gpu overflow-hidden blur-3xl sm:-top-80">
          <div className="relative left-[calc(50%-11rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 rotate-[30deg] bg-gradient-to-tr from-indigo-500 to-purple-600 opacity-20 sm:left-[calc(50%-30rem)] sm:w-[72.1875rem]" />
        </div>

        <div className="mx-auto max-w-7xl px-6 pb-24 pt-10 sm:pb-32 lg:flex lg:px-8 lg:py-40">
          <div className="mx-auto max-w-2xl flex-shrink-0 lg:mx-0 lg:max-w-xl lg:pt-8">
            {/* Badge */}
            <div className="mt-24 sm:mt-32 lg:mt-16">
              <span className="inline-flex items-center gap-x-1.5 rounded-full bg-indigo-500/10 px-3 py-1 text-sm font-semibold text-indigo-400 ring-1 ring-inset ring-indigo-500/20">
                <span className="h-1.5 w-1.5 rounded-full bg-indigo-400" />
                AI-Powered
              </span>
            </div>

            <h1 className="mt-10 text-4xl font-bold tracking-tight text-white sm:text-6xl">
              Your Developer Portfolio,{" "}
              <span className="text-indigo-400">Generated by AI</span>
            </h1>

            <p className="mt-6 text-lg leading-8 text-gray-300">
              Connect your GitHub, let AI analyze your projects and skills, and
              get a professional CV in under 5 minutes. No design skills needed.
            </p>

            <div className="mt-10 flex items-center gap-x-6">
              <Link
                href="/login"
                id="cta-github-login"
                className="flex items-center gap-2 rounded-lg bg-indigo-600 px-6 py-3 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 transition-all duration-200 hover:scale-105"
              >
                <svg className="h-5 w-5" viewBox="0 0 24 24" fill="currentColor">
                  <path fillRule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clipRule="evenodd" />
                </svg>
                Continue with GitHub
              </Link>
              <Link
                href="/templates"
                id="cta-view-templates"
                className="text-sm font-semibold leading-6 text-gray-300 hover:text-white transition-colors"
              >
                View Templates <span aria-hidden="true">→</span>
              </Link>
            </div>
          </div>
        </div>
      </div>

      {/* Features Section */}
      <div className="mx-auto max-w-7xl px-6 lg:px-8 pb-24">
        <div className="grid grid-cols-1 gap-8 sm:grid-cols-3">
          {[
            {
              title: "Connect GitHub",
              desc: "Login with GitHub OAuth. We analyze your repos, stars, languages automatically.",
              icon: "🔗",
            },
            {
              title: "AI Generates CV",
              desc: "GPT-4o analyzes your projects and writes professional descriptions for you.",
              icon: "🤖",
            },
            {
              title: "Share & Export",
              desc: "Get a public portfolio URL and export to PDF in one click.",
              icon: "🚀",
            },
          ].map((f) => (
            <div
              key={f.title}
              className="rounded-2xl bg-white/5 p-8 ring-1 ring-white/10 hover:bg-white/10 transition-all duration-200"
            >
              <div className="text-4xl mb-4">{f.icon}</div>
              <h3 className="text-lg font-semibold text-white">{f.title}</h3>
              <p className="mt-2 text-sm text-gray-400">{f.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </main>
  );
}
